version: '3'
services:
    weather-app:
        container_name: weather-app
        build: .
        volumes:
            - ".:/usr/src/app"
        ports:
            - "80:3000"
        command: npm start
        restart: always
        links:
            - "web"
    web:
        image: nginx:alpine
        volumes:
            - "./config/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./config/etc/ssl:/etc/ssl"
            - "./server:/var/www/html/public"
            - "./config/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./server:/var/www/html/public"
networks:
    default:
        driver: bridge